# Generated by Django 4.1.2 on 2022-10-13 08:52

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0004_user_hackathon_participant"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="participants",
            field=models.ManyToManyField(
                blank=True, related_name="event", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
